<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/action/">Akce</a></li>
    <li class="current"><a href="#">Přidat Akci</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="widgetbox">
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Základní info</span></h2>
        </div><!--contenttitle-->

        <form class="stdform stdform2" method="post" action="#" >
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
            <p>
                <label>Název*</label>
                <span class="field">
                    <input type="text" name="title" class="longinput" value="{echo isset($action)? $action->title: ""}" />
                    {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Pořadí<small>Max. 99</small></label>
                <span class="field">
                    <input type="text" name="rank" class="longinput" value="{echo isset($action)? $action->rank: 1}"/>
                    {if isset($errors["rank"])}
                    <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Zobrazovat do*</label>
                <span class="field">
                    <input type="text" name="expiration" class="longinput datepicker" 
                           value="{echo isset($action)? $action->expirationDate: ""}"/>
                    {if isset($errors["expirationDate"])}
                    <label class="error">{echo join("<br/>", $errors["expirationDate"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Teaser*<small>Max. 750 znaků</small></label>
                <span class="field">
                    <textarea rows="20" name="shorttext" id="ckeditor2">{echo isset($action)? $action->shortBody: ""}</textarea>
                    {if isset($errors["shortBody"])}
                    <label class="error">{echo join("<br/>", $errors["shortBody"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-teaser">Smazat</button>
                    <button id="teaser-new-paragraph">Nový odstavec</button>
                    <button id="teaser-readmore-link">Přidat odkaz na celý článek</button>
                    <button id="teaser-to-text">Zkopírovat do Text</button>
                    <button id="teaser-link-to-gallery">Odkaz na galerii</button>
                    <button id="teaser-link-to-action">Odkaz na akci</button>
                    <button id="teaser-link-to-news">Odkaz na novinku</button>
                    <button id="teaser-link-to-report">Odkaz na reportáž</button>
                    <button id="teaser-link-to-content">Odkaz na stránku</button>
                </span>
            </p>
            <p>
                <label>Text*</label>
                <span class="field">
                    <textarea rows="20" name="text" id="ckeditor">{echo isset($action)? $action->body: ""}</textarea>
                    {if isset($errors["body"])}
                    <label class="error">{echo join("<br/>", $errors["body"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-text">Smazat</button>
                    <button id="text-new-paragraph">Nový odstavec</button>
                    <button id="text-to-teaser">Zkopírovat do Teaser</button>
                    <button id="text-link-to-gallery">Odkaz na galerii</button>
                    <button id="text-link-to-action">Odkaz na akci</button>
                    <button id="text-link-to-news">Odkaz na novinku</button>
                    <button id="text-link-to-report">Odkaz na reportáž</button>
                    <button id="text-link-to-content">Odkaz na stránku</button>
                </span>
            </p>
            <p>
                <label>Datum - začátek</label>
                <span class="field">
                    Datum: <input type="text" name="datestart" class="microinput datepicker2" 
                                  value="{echo isset($action)? $action->startDate: ""}"/>
                    Čas: <input type="time" name="timestart" class="microinput" 
                                value="{echo isset($action)? $action->startTime: ""}"/>
                    {if isset($errors["startDate"])}
                    <label class="error">{echo join("<br/>", $errors["startDate"])}</label>
                    {/if}
                    {if isset($errors["startTime"])}
                    <label class="error">{echo join("<br/>", $errors["startTime"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Datum - konec</label>
                <span class="field">
                    Datum: <input type="text" name="dateend" class="microinput datepicker3" 
                                  value="{echo isset($action)? $action->endDate: ""}"/>
                    Čas: <input type="time" name="timeend" class="microinput" 
                                value="{echo isset($action)? $action->endTime: ""}"/>
                    {if isset($errors["endDate"])}
                    <label class="error">{echo join("<br/>", $errors["endDate"])}</label>
                    {/if}
                    {if isset($errors["endTime"])}
                    <label class="error">{echo join("<br/>", $errors["endTime"])}</label>
                    {/if}
                </span>
            </p>

            <br/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Metadata</span></h2>
            </div><!--contenttitle-->
            <p>
                <label>Meta-název</label>
                <span class="field">
                    <input type="text" name="metatitle" class="longinput" value="{echo isset($action)? $action->metaTitle: ""}" />
                    {if isset($errors["metaTitle"])}
                    <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Meta-popis</label>
                <span class="field">
                    <textarea rows="5" name="metadescription" class="longinput" >{echo isset($action)? $action->metaDescription: ""}</textarea>
                    {if isset($errors["metaDescription"])}
                    <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                    {/if}
                    <br/>
                </span>
            </p>
            <p>
                <label>Klíčová slova<small>Pro interní vyhledávač</small></label>
                <span class="field">
                    <input type="text" name="keywords" class="longinput" value="{echo isset($action)? $action->keywords: ""}" 
                           placeholder="Oddělovač: mezera"/>
                    {if isset($errors["keywords"])}
                    <label class="error">{echo join("<br/>", $errors["keywords"])}</label>
                    {/if}
                </span>
            </p>

            <p class="stdformbutton">
                <input name="submitAddAction" type="submit" value="Uložit" class="submit radius2" />
                <input type="reset" class="reset radius2" value="Reset" />
            </p>
        </form>
    </div>
</div>
<br class="clear-all"/>
<div id="insert-dialog"><p></p></div>
<script type="text/javascript" src="/public/js/custom/news.js"></script>