<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Application</title>
        <!---CSS Files-->
        <link rel="stylesheet" href="/public/css/custom/errorStyle.min.css">
    </head>
    <body lang="en">
        <div class="content container_12">
            <h1 id="error-heading">Údržba</h1>
            <p id="error-desc">Právě probíhá údržba našeho webu</p>
            <p id="error-desc">Brzy budeme zpět</p>
        </div>
        
        <div class="footer container_12">
            <p class="grid_12">Váš Hastrman</p>
        </div>

    </body>
</html>
