<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Analytics</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="one_third">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Počet návštěvníků - realtime</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Live&actionToWidgetize=getSimpleLastVisitCount&idSite=1&period=week&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="two_third last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Graf návštěv</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&columns[]=nb_visits&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=1&period=week&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Doba návštěv</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=VisitorInterest&actionToWidgetize=getNumberOfVisitsPerVisitDuration&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Návštěvy podle dne</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=VisitTime&actionToWidgetize=getByDayOfWeek&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Stránky</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="500" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Titulky stránek</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="500" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageTitles&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Webové prohlížeče</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserSettings&actionToWidgetize=getBrowserVersion&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Mapa návštěvníků</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountryMap&actionToWidgetize=visitorMap&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Rozlišení obrazovky</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350" src="//piwik.hastrman.cz/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserSettings&actionToWidgetize=getResolution&idSite=1&period=year&date=today&disableLink=1&widget=1&token_auth=e49c4884f0eb21411273f82ba739984e" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />
</div>