<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Novinky</a></li>
    <li><a href="/admin/news/add/">Přidat novinku</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Novinky</span></h2>
    </div><!--contenttitle-->
    
    <form method="post" class="massActionForm" action="/admin/news/massaction/">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
            <colgroup>
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
            </colgroup>
            <thead>
                <tr>
                    <td class="head0 width50"><input type="checkbox" class="checkall" /></td>
                    <td class="head1">Název</td>
                    <td class="head0">Autor</td>
                    <td class="head1">Zobrazovat do</td>
                    <td class="head0">Vytvořeno</td>
                    <td class="head1">Stav</td>
                    <td class="head0">V archivu</td>
                    <td class="head1">&nbsp;</td>
                </tr>
            </thead>
            <tbody>
                {if !empty($news)}
                    {foreach $_news in $news}
                        <tr>
                            <td class="center">
                                <input type="checkbox" name="newsids[]" value="{echo $_news->getId()}" />
                            </td>
                            <td>{echo $_news->getTitle()}</td>
                            <td>{echo $_news->getUserAlias()}</td>
                            <td>{echo $_news->getExpirationDate()}</td>
                            <td>{echo $_news->getCreated()}</td>
                            <td>
                                {if ($_news->approved == 1)}
                                    {if $_news->active}<span class="labelProduct labelProductGreen">Aktivní</span>{/if}
                                {/if}{elseif $_news->approved == 2}
                                    <span class="labelProduct labelProductRed">Zamítnuto</span>
                                {/elseif}{else}
                                    <span class="labelProduct labelProductOrange">Čeká na schválení</span>
                                {/else}
                            </td>
                            <td>
                                {if $_news->archive}<span class="labelProduct labelProductGreen">Ano</span>{/if}
                                {else}<span class="labelProduct labelProductGray">Ne</span>{/else}
                            </td>
                            <td>
                                <a href="/admin/news/edit/{echo $_news->id}" class="btn btn3 btn_pencil" title="Upravit"></a>
                                {if $isAdmin || $_news->userId == $authUser->id}
                                    <a href="/admin/news/delete/{echo $_news->id}" class="btn btn3 btn_trash ajaxBtn" title="Smazat"></a>
                                {/if}
                                {if $isAdmin && $_news->approved == 0}
                                    <a href="/admin/news/approvenews/{echo $_news->id}" class="btn btn3 btn_info ajaxBtnReload" title="Schválit"></a>
                                    <a href="/admin/news/rejectnews/{echo $_news->id}" class="btn btn3 btn_stop ajaxBtnReload" title="Zamítnout"></a>
                                {/if}
                            </td>
                        </tr>
                    {/foreach}
                {/if}
            </tbody>
        </table>
        {if $isAdmin}
        <div class="tableoptions">
            Selected:
            <select class="radius3" name="action">
                <option value="activate">Aktivovat</option>
                <option value="deactivate">Deaktivovat</option>
                <option value="delete">Smazat</option>
            </select> &nbsp;
            <input class="radius3" type="submit" name="performNewsAction" value="Provést"/>
        </div><!--tableoptions-->
        {/if}
    </form>
</div>
<br class="clear-all"/><br />