<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/report/">Reportáže</a></li>
    <li class="current"><a href="#">Přidat Reportáž</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="widgetbox">
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Základní info</span></h2>
        </div><!--contenttitle-->

        <form class="stdform stdform2 cropit-form" method="post" action="#" enctype="multipart/form-data">
            <input type="hidden" name="MAX_FILE_SIZE" value="15000000"/>
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
            <input type="hidden" name="croppedimage" class="cropit-hidden-resized-image" value="" />

            <p>
                <label>Název*</label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::textInput('title', array($report,'title'), true)}
                    {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Pořadí<small>Max. 99</small></label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::textInput('rank', array($report,'rank',1))}
                    {if isset($errors["rank"])}
                    <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Teaser*<small>Max. 750 znaků</small></label>
                <span class="field">
                    <textarea rows="20" name="shorttext" id="ckeditor2">{echo isset($report)? $report->shortBody: ""}</textarea>
                    {if isset($errors["shortBody"])}
                    <label class="error">{echo join("<br/>", $errors["shortBody"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-teaser">Smazat</button>
                    <button id="teaser-new-paragraph">Nový odstavec</button>
                    <button id="teaser-readmore-link">Přidat odkaz na celý článek</button>
                    <button id="teaser-to-text">Zkopírovat do Text</button>
                    <button id="teaser-link-to-gallery">Odkaz na galerii</button>
                    <button id="teaser-link-to-action">Odkaz na akci</button>
                    <button id="teaser-link-to-news">Odkaz na novinku</button>
                    <button id="teaser-link-to-report">Odkaz na reportáž</button>
                    <button id="teaser-link-to-content">Odkaz na stránku</button>
                </span>
            </p>
            <p>
                <label>Text*</label>
                <span class="field">
                    <textarea rows="20" name="text" id="ckeditor">{echo isset($report)? $report->body: ""}</textarea>
                    {if isset($errors["body"])}
                    <label class="error">{echo join("<br/>", $errors["body"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-text">Smazat</button>
                    <button id="text-new-paragraph">Nový odstavec</button>
                    <button id="text-to-teaser">Zkopírovat do Teaser</button>
                    <button id="text-link-to-gallery">Odkaz na galerii</button>
                    <button id="text-link-to-action">Odkaz na akci</button>
                    <button id="text-link-to-news">Odkaz na novinku</button>
                    <button id="text-link-to-report">Odkaz na reportáž</button>
                    <button id="text-link-to-content">Odkaz na stránku</button>
                </span>
            </p>

            <br/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Metadata</span></h2>
            </div><!--contenttitle-->
            <p>
                <label>Meta-název</label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::textInput('metatitle', array($report,'metaTitle'), false, 'longinput', "Výchozí hodnota: stejná jako Název")}
                    {if isset($errors["metaTitle"])}
                    <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Meta-popis</label>
                <span class="field">
                    <textarea rows="5" name="metadescription" class="longinput" >{echo \Admin\Helper\FormPrinter::iset($report,'metaDescription')}</textarea>
                    {if isset($errors["metaDescription"])}
                    <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                    {/if}
                    <br/>
                </span>
            </p>
            <p>
                <label>Klíčová slova<small>Pro interní vyhledávač</small></label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::textInput('keywords', array($report,'keywords'), false, 'longinput', "Oddělovač: mezera")}
                    {if isset($errors["keywords"])}
                    <label class="error">{echo join("<br/>", $errors["keywords"])}</label>
                    {/if}
                </span>
            </p>

            <br/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Pozadí pro reportáž</span></h2>
            </div><!--contenttitle-->
            <div class="par">
                <label>Foto*<small>*.jpg, *.jpeg, *.png, *.gif<br/>Max. 15MB</small></label>
                {if isset($report) && $report->imgMain != ""}
                <span class="field" id="currentLogo">
                    <img src="{echo $report->imgThumb}" alt="" height="100" />
                    <a href="/admin/report/previewdeletephoto/" class="btn btn3 btn_trash deleteImg" title="Smazat"></a>
                </span>

                <div id="image-cropper" class="uploadNewImage nodisplay field">
                    <input type="file" class="cropit-image-input" accept="image/*"/>
                    <div class="cropit-image-preview-container">
                        <div class="cropit-image-background-container">
                            <img class="cropit-image-background" />
                        </div>
                        <div class="cropit-image-preview"></div>
                    </div>

                    <input type="range" class="cropit-image-zoom-input" />
                    {if isset($errors["croppedimage"])}
                    <label class="error">
                        {echo join("<br/>", $errors["croppedimage"])}
                    </label>
                    {/if}
                </div>
                {/if}{else}
                <div id="image-cropper" class="uploadNewImage field">
                    <input type="file" class="cropit-image-input" accept="image/*"/>
                    <div class="cropit-image-preview-container">
                        <div class="cropit-image-background-container">
                            <img class="cropit-image-background" />
                        </div>
                        <div class="cropit-image-preview"></div>
                    </div>

                    <input type="range" class="cropit-image-zoom-input" />
                    {if isset($errors["croppedimage"])}
                    <label class="error">
                        {echo join("<br/>", $errors["croppedimage"])}
                    </label>
                    {/if}
                </div>
                {/else}
            </div>

            <p class="stdformbutton">
                <input name="submitAddReport" type="submit" value="Uložit" class="submit radius2" />
                <input name="submitPreviewReport" type="submit" value="Zobrazit náhled" class="submit radius2" />
                <input type="reset" class="reset radius2" value="Reset" />
            </p>
        </form>
    </div>
</div>
<br class="clear-all"/>
<div id="insert-dialog"><p></p></div>
<script type="text/javascript" src="/public/js/custom/news.js"></script>