<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/report/">Reportáže</a></li>
    <li><a href="/admin/report/add/">Přidat Reportáž</a></li>
    <li class="current"><a href="#">Upravit Reportáž</a></li>
    <li><a href="/admin/report/help/">Nápověda</a></li>
</ul><!--maintabmenu-->

{if isset($report)}
<div class="content">
    <div id="tabs">
        <ul>
            <li><a href="#basic">Základní údaje</a></li>
            <li><a href="#comments">Komentáře</a></li>
        </ul>
        <div class="widgetbox" id="basic">
            {if !empty($concepts)}
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Koncepty</span></h2>
            </div><!--contenttitle-->
            <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                <colgroup>
                    <col class="con0" /> <col class="con1" />
                </colgroup>
                <thead>
                    <tr>
                        <td class="head0">Vytvořeno</td>
                        <td class="head1">Poslední změna</td>
                        <td class="head0">&nbsp;</td>
                    </tr>
                </thead>
                {foreach $concept in $concepts}
                <tr>
                    <td>{echo $concept->getCreated()}</td>
                    <td>{echo $concept->getModified()}</td>
                    <td><a href="/admin/report/loadconcept/{echo $concept->getId()}" class="btn btn3 btn_pencil ajaxLoadConcept" title="Načíst concept"></a>
                        <a href="/admin/concept/delete/{echo $concept->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat concept"></a></td>
                </tr>
                {/foreach}
            </table>
            {/if}

            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Základní info</span></h2>
            </div><!--contenttitle-->

            <form class="stdform stdform2 cropit-form" method="post" action="#" enctype="multipart/form-data">
                <input type="hidden" name="MAX_FILE_SIZE" value="15000000"/>
                <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
                <input type="hidden" name="conceptid" id="conceptid" value="{echo isset($conceptid) ? $conceptId:0}" />
                <input type="hidden" name="concepttype" id="concepttype" value="3" />
                <input type="hidden" name="croppedimage" class="cropit-hidden-resized-image" value="" />

                <p>
                    <label>Název*</label>
                    <span class="field">
                        {echo \Admin\Helper\FormPrinter::textInput('title', array($report,'title'), true)}
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Pořadí<small>Max. 99</small></label>
                    <span class="field">
                        {echo \Admin\Helper\FormPrinter::textInput('rank', array($report,'rank',1))}
                        {if isset($errors["rank"])}
                        <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Teaser*<small>Max. 750 znaků</small></label>
                    <span class="field">
                        <textarea rows="20" name="shorttext" id="ckeditor2">{echo $report->shortBody}</textarea>
                        {if isset($errors["shortBody"])}
                        <label class="error">{echo join("<br/>", $errors["shortBody"])}</label>
                        {/if}
                        <br/>
                        <button id="clear-teaser">Smazat</button>
                        <button id="teaser-new-paragraph">Nový odstavec</button>
                        <button id="teaser-readmore-link">Přidat odkaz na celý článek</button>
                        <button id="teaser-to-text">Zkopírovat do Text</button>
                        <button id="teaser-link-to-gallery">Odkaz na galerii</button>
                        <button id="teaser-link-to-action">Odkaz na akci</button>
                        <button id="teaser-link-to-news">Odkaz na novinku</button>
                        <button id="teaser-link-to-report">Odkaz na reportáž</button>
                        <button id="teaser-link-to-content">Odkaz na stránku</button>
                    </span>
                </p>
                <p>
                    <label>Text*</label>
                    <span class="field">
                        <textarea rows="20" name="text" id="ckeditor">{echo $report->body}</textarea>
                        {if isset($errors["body"])}
                        <label class="error">{echo join("<br/>", $errors["body"])}</label>
                        {/if}
                        <br/>
                        <button id="clear-text">Smazat</button>
                        <button id="text-new-paragraph">Nový odstavec</button>
                        <button id="text-to-teaser">Zkopírovat do Teaser</button>
                        <button id="text-link-to-gallery">Odkaz na galerii</button>
                        <button id="text-link-to-action">Odkaz na akci</button>
                        <button id="text-link-to-news">Odkaz na novinku</button>
                        <button id="text-link-to-report">Odkaz na reportáž</button>
                        <button id="text-link-to-content">Odkaz na stránku</button>
                    </span>
                </p>

                <br/>
                <div class="contenttitle radiusbottom0">
                    <h2 class="table"><span>Systémové info</span></h2>
                </div><!--contenttitle-->
                <p>
                    <label>Aktivní</label>
                    <span class="field">
                        <select name="active" class="width80">
                            {if $report->active}
                            <option value="0">Neaktivní</option>
                            <option value="1" selected>Aktivní</option>
                            {/if}{else}
                            <option value="0" selected>Neaktivní</option>
                            <option value="1">Aktivní</option>
                            {/else}
                        </select>
                    </span>
                </p>
                <p>
                    <label>Schváleno</label>
                    <span class="field">
                        <select name="approve" class="width80">
                            {if $report->approved == 0}
                            <option value="0" selected>Čeká na shválení</option>
                            <option value="1">Schváleno</option>
                            <option value="2">Zamítnuto</option>
                            {/if}{elseif $report->approved == 1}
                            <option value="0">Čeká na shválení</option>
                            <option value="1" selected>Schváleno</option>
                            <option value="2">Zamítnuto</option>
                            {/elseif}{else}
                            <option value="0">Čeká na shválení</option>
                            <option value="1">Schváleno</option>
                            <option value="2" selected>Zamítnuto</option>
                            {/else}
                        </select>
                    </span>
                </p>
                <p>
                    <label>V archivu</label>
                    <span class="field">
                        <select name="archive" class="width80">
                            {if $report->archive}
                            <option value="0">Ne</option>
                            <option value="1" selected>Ano</option>
                            {/if}{else}
                            <option value="0" selected>Ne</option>
                            <option value="1">Ano</option>
                            {/else}
                        </select>
                    </span>
                </p>

                <br/>
                <div class="contenttitle radiusbottom0">
                    <h2 class="table"><span>Metadata</span></h2>
                </div><!--contenttitle-->
                <p>
                    <label>Meta-název</label>
                    <span class="field">
                        {echo \Admin\Helper\FormPrinter::textInput('metatitle', array($report,'metaTitle'), false, 'width80', "Výchozí hodnota: stejná jako Název")}
                        {if isset($errors["metaTitle"])}
                        <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-popis</label>
                    <span class="field">
                        <textarea rows="5" name="metadescription" class="width80" >{echo \Admin\Helper\FormPrinter::iset($report,'metaDescription')}</textarea>
                        {if isset($errors["metaDescription"])}
                        <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                        {/if}
                        <br/>
                    </span>
                </p>
                <p>
                    <label>Klíčová slova<small>Pro interní vyhledávač</small></label>
                    <span class="field">
                        {echo \Admin\Helper\FormPrinter::textInput('keywords', array($report,'keywords'), false, 'width80', "Oddělovač: mezera")}
                        {if isset($errors["keywords"])}
                        <label class="error">{echo join("<br/>", $errors["keywords"])}</label>
                        {/if}
                    </span>
                </p>

                <br/>
                <div class="contenttitle radiusbottom0">
                    <h2 class="table"><span>Pozadí pro reportáž</span></h2>
                </div><!--contenttitle-->
                <div class="par">
                    <label>Foto*<small>*.jpg, *.jpeg, *.png, *.gif<br/>Max. 15MB</small></label>
                    {if $report->imgMain != ""}
                    <span class="field" id="currentLogo">
                        <img src="{echo $report->imgThumb}" alt="" height="100" />
                        <a href="/admin/report/deletemainphoto/{echo $report->id}" class="btn btn3 btn_trash deleteImg" title="Smazat"></a>
                    </span>

                    <div id="image-cropper" class="uploadNewImage nodisplay field">
                        <input type="file" class="cropit-image-input" accept="image/*"/>
                        <div class="cropit-image-preview-container">
                            <div class="cropit-image-background-container">
                                <img class="cropit-image-background" />
                            </div>
                            <div class="cropit-image-preview"></div>
                        </div>

                        <input type="range" class="cropit-image-zoom-input" />
                        {if isset($errors["croppedimage"])}
                        <label class="error">
                            {echo join("<br/>", $errors["croppedimage"])}
                        </label>
                        {/if}
                    </div>
                    {/if}{else}
                    <div id="image-cropper" class="uploadNewImage field">
                        <input type="file" class="cropit-image-input" accept="image/*"/>
                        <div class="cropit-image-preview-container">
                            <div class="cropit-image-background-container">
                                <img class="cropit-image-background" />
                            </div>
                            <div class="cropit-image-preview"></div>
                        </div>

                        <input type="range" class="cropit-image-zoom-input" />
                        {if isset($errors["croppedimage"])}
                        <label class="error">
                            {echo join("<br/>", $errors["croppedimage"])}
                        </label>
                        {/if}
                    </div>
                    {/else}
                </div>

                <p class="stdformbutton">
                    <input name="submitEditReport" type="submit" value="Uložit" class="submit radius2" />
                    <input name="submitPreviewReport" type="submit" value="Zobrazit náhled" class="submit radius2" />
                </p>
            </form>
        </div>

        <div class="widgetbox" id="comments">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Komentáře</span></h2>
            </div><!--contenttitle-->

            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
                <colgroup>
                    <col class="con0" /><col class="con1" />
                    <col class="con0" /><col class="con1" />
                    <col class="con0" />
                </colgroup>
                <thead>
                    <tr>
                        <td class="head0">Id</td><td class="head1">Autor</td>
                        <td class="head0">Text</td><td class="head1">Vytvořeno</td>
                        <td class="head0">&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                    {if (!empty($comments))}
                    {macro showReplies($replies)}
                    {foreach $reply in $replies}
                    <tr>
                        <td class="alignright">=></td>
                        <td>{echo $reply->getFirstname()." ".$reply->getLastname()}</td>
                        <td>{echo $reply->getBody()}</td>
                        <td>{echo $reply->getCreated()}</td>

                        <td>
                            <a href="/admin/comment/delete/{echo $reply->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                        </td>
                    </tr>
                    {if !empty($reply->_replies)}
                    {echo showReplies($reply->_replies)}
                    {/if}
                    {/foreach}
                    {/macro}

                    {foreach $comment in $comments}
                    <tr>
                        <td>{echo $comment->getId()}</td>
                        <td>{echo $comment->getFirstname()." ".$comment->getLastname()}</td>
                        <td>{echo $comment->getBody()}</td>
                        <td>{echo $comment->getCreated()}</td>

                        <td>
                            <a href="/admin/comment/delete/{echo $comment->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                        </td>
                    </tr>

                    {if !empty($comment->_replies)}
                    {echo showReplies($comment->_replies)}
                    {/if}
                    {/foreach}
                    {/if}
                </tbody>
            </table>
        </div>
    </div>
</div>
<br class="clear-all"/>
<div id="insert-dialog"><p></p></div>
<script type="text/javascript" src="/public/js/custom/build/news.js"></script>
{/if}