<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Reportáže</a></li>
    <li><a href="/admin/report/add/">Přidat Reportáž</a></li>
    <li><a href="/admin/report/help/">Nápověda</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Reportáže</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <input type="hidden" name="type" id="type" value="report" />

    {if $isAdmin}
    <div class="tableoptions">
        <select class="radius3" name="selection">
            <option value="1">Označené</option>
            <option value="2">Aktuální stránka</option>
        </select>
        <select class="radius3" name="action">
            <option value="activate">Aktivovat</option>
            <option value="deactivate">Deaktivovat</option>
            <option value="approve">Schválit</option>
            <option value="reject">Zamítnout</option>
            <option value="delete">Smazat</option>
        </select> &nbsp;
        <a class="btn btn_document ajax-massaction" href="/admin/report/massaction/"><span>Proveď</span></a>
    </div><!--tableoptions-->
    {/if}
    <table border="0" class="stdtable2">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0 width50">Id</td>
                <td class="head1">Název</td>
                <td class="head0">Autor</td>
                <td class="head1">Vytvořeno</td>
                <td class="head0">Upraveno</td>
                <td class="head1">Stav</td>
                <td class="head0">&nbsp;</td>
            </tr>
        </thead>
    </table>
    {if $isAdmin}
    <div class="tableoptions">
        <select class="radius3" name="selection">
            <option value="1">Označené</option>
            <option value="2">Aktuální stránka</option>
        </select>
        <select class="radius3" name="action">
            <option value="activate">Aktivovat</option>
            <option value="deactivate">Deaktivovat</option>
            <option value="approve">Schválit</option>
            <option value="reject">Zamítnout</option>
            <option value="delete">Smazat</option>
        </select> &nbsp;
        <a class="btn btn_document ajax-massaction" href="/admin/report/massaction/"><span>Proveď</span></a>
    </div><!--tableoptions-->
    {/if}
</div>
<br class="clear-all"/><br />