<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">Uživatelé</a></li>
    <li><a href="/admin/user/add/">Nový uživatel</a></li>
    <li class="current"><a href="#">Editovat uživatele</a></li>
</ul>

{if isset($user)}
<div class="content">
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Osobní údaje</span></h2>
        </div>
        <p>
            <label>Jméno*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::textInput('firstname', array($user,'firstname'), true)}
                {if isset($errors["firstname"])}
                <label class="error">
                    {echo join("<br/>", $errors["firstname"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Příjmení*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::textInput('lastname', array($user,'lastname'), true)}
                {if isset($errors["lastname"])}
                <label class="error">
                    {echo join("<br/>", $errors["lastname"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Telefon</label>
            <span class="field">
                <input type="tel" name="phone" class="longinput" value="{echo $user->phoneNumber}" />
                {if isset($errors["phoneNumber"])}
                <label class="error">
                    {echo join("<br/>", $errors["phoneNumber"])}
                </label>
                {/if}
            </span>
        </p>
        
        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Přihlašovací údaje</span></h2>
        </div>
        <p>
            <label>Email*</label>
            <span class="field">
                <input required type="email" name="email" class="longinput" value="{echo $user->email}" />
                {if isset($errors["email"])}
                <label class="error">
                    {echo join("<br/>", $errors["email"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Heslo*</label>
            <span class="field">
                <input type="password" name="password" class="longinput" value=""/>
                {if isset($errors["password"])}
                <label class="error">
                    {echo join("<br/>", $errors["password"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Potvrdit heslo*</label>
            <span class="field">
                <input type="password" name="password2" class="longinput" value=""/>
                {if isset($errors["password2"])}
                <label class="error">
                    {echo join("<br/>", $errors["password2"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $user->active == 1}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/if}{else}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Zablokován</label>
            <span class="field">
                <select name="blocked" class="longinput">
                    {if $user->blocked == 1}
                    <option value="0">Účet není zablokovaný</option>
                    <option value="1" selected>Zablokován</option>
                    {/if}{else}
                    <option value="0" selected>Účet není zablokovaný</option>
                    <option value="1">Zablokován</option>
                    {/else}
                </select>
            </span>
        </p>

        {if $isSuperAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="longinput">
                    {if $user->role == "role_superadmin"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin" selected>Super Admin</option>
                    {/if}
                    {elseif $user->role == "role_admin"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin" selected>Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/elseif}{elseif $user->role == "role_participant"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant" selected>Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/elseif}{else}
                    <option value="role_member" selected>Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/else}
                </select>
                {if isset($errors["role"])}
                <label class="error">
                    {echo join("<br/>", $errors["role"])}
                </label>
                {/if}
            </span>
        </p>
        {/if}
        {elseif $isAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="longinput">
                    {if $user->role == "role_admin"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin" selected>Admin</option>
                    {/if}{elseif $user->role == "role_participant"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant" selected>Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    {/elseif}{else}
                    <option value="role_member" selected>Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    {/else}
                </select>
                {if isset($errors["role"])}
                <label class="error">
                    {echo join("<br/>", $errors["role"])}
                </label>
                {/if}
            </span>
        </p>
        {/elseif}
        
        <p class="stdformbutton">
            <input type="submit" name="submitEditUser" value="Uložit" class="submit radius2"/>
        </p>
    </form>
</div>
{/if}