<script type="text/javascript" src="/public/js/custom/dashboard.js"></script>
<ul class="maintabmenu">
    <li class="current"><a href="/admin/">Dashboard</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="one_half">
        <div class="contenttitle">
            <h2 class="button"><span>Přidat</span></h2>
        </div><!--contenttitle-->
        <ul class="widgetlist">
            <li><a href="/admin/news/add/" class="message">Novinku</a></li>
            <li><a href="/admin/action/add/" class="events">Akci</a></li>
            <li><a href="/admin/report/add/" class="message">Reportáž</a></li>
            <li><a href="/admin/gallery/add/" class="upload">Galerii</a></li>
            <li><a href="/admin/document/upload/" class="upload">Dokument</a></li>
        </ul>
    </div>

    <br clear="all" /><br />
    
    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Poslední novinky</span></h2></div>
            <div class="widgetcontent announcement">
                {if !empty($latestnews)}
                    {foreach $news in $latestnews}
                        <p>
                            <span class="radius2">Název: {echo $news->getTitle()}</span>
                            <span class="radius2">Vytvořeno: {echo $news->getCreated()}</span>
                            <span class="radius2">Stav: 
                                {if $news->getApproved() == 0}Čeká na schválení{/if}
                                {elseif $news->getApproved() == 1}Schváleno{/elseif}
                                {else}Zamítnuto{/else}
                            </span>
                            <br/><br/>
                            {echo $news->shortBody}
                        </p>
                        <hr/>
                    {/foreach}
                {/if}{else}
                <p>Žádné aktuality</p>
                {/else}
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <br class="clear-all"/><br />
    
    <div class="one_half ">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější Reportáže</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestreports)}
                            {foreach $report in $latestreports}
                                <tr>
                                    <td>{echo $report->getTitle()}</td>
                                    <td>{echo $report->firstname." ".$action->lastname}</td>
                                    <td>{echo $report->getCreated()}</td>
                                    <td>
                                        {if $report->getApproved() == 0}Čeká na schválení{/if}
                                        {elseif $report->getApproved() == 1}Schváleno{/elseif}
                                        {else}Zamítnuto{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější Akce</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestactions)}
                            {foreach $action in $latestactions}
                                <tr>
                                    <td>{echo $action->getTitle()}</td>
                                    <td>{echo $action->firstname." ".$action->lastname}</td>
                                    <td>{echo $action->getCreated()}</td>
                                    <td>
                                        {if $action->getApproved() == 0}Čeká na schválení{/if}
                                        {elseif $action->getApproved() == 1}Schváleno{/elseif}
                                        {else}Zamítnuto{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
</div><!--content-->