<ul class="maintabmenu">
    <li class="current"><a href="/admin/">Dashboard</a></li>
</ul><!--maintabmenu-->

<div class="content">
    {include imessages.phtml}
    <div class="one_half">
        <div class="contenttitle">
            <h2 class="button"><span>Přidat</span></h2>
        </div><!--contenttitle-->
        <ul class="widgetlist">
            <li><a href="/admin/news/add/" class="message">Novinku</a></li>
            <li><a href="/admin/action/add/" class="events">Akci</a></li>
            <li><a href="/admin/report/add/" class="message">Reportáž</a></li>
            <li><a href="/admin/gallery/add/" class="upload">Galerii</a></li>
            {if $isAdmin}<li><a href="/admin/partner/add/" class="upload">Partnera</a></li>{/if}
        </ul>
    </div>

    <br clear="all" /><br />
    
    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Poslední novinky</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestnews)}
                            {foreach $news in $latestnews}
                                <tr>
                                    <td><a href="/admin/news/edit/{echo $news->getId()}">{echo $news->getTitle()}</a></td>
                                    <td>{echo $news->getUserAlias()}</td>
                                    <td>{echo $news->getCreated()}</td>
                                    <td>
                                        {if $news->getApproved() == 0}Čeká na schválení{/if}
                                        {elseif $news->getApproved() == 1}Schváleno{/elseif}
                                        {else}Zamítnuto{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější Akce</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestactions)}
                            {foreach $action in $latestactions}
                                <tr>
                                    <td><a href="/admin/action/edit/{echo $action->getId()}">{echo $action->getTitle()}</a></td>
                                    <td>{echo $action->getUserAlias()}</td>
                                    <td>{echo $action->getCreated()}</td>
                                    <td>
                                        {if $action->getApproved() == 0}Čeká na schválení{/if}
                                        {elseif $action->getApproved() == 1}Schváleno{/elseif}
                                        {else}Zamítnuto{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    <br class="clear-all"/><br />
    
    <div class="one_half ">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější Reportáže</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestreports)}
                            {foreach $report in $latestreports}
                                <tr>
                                    <td><a href="/admin/report/edit/{echo $report->getId()}">{echo $report->getTitle()}</a></td>
                                    <td>{echo $report->getUserAlias()}</td>
                                    <td>{echo $report->getCreated()}</td>
                                    <td>
                                        {if $report->getApproved() == 0}Čeká na schválení{/if}
                                        {elseif $report->getApproved() == 1}Schváleno{/elseif}
                                        {else}Zamítnuto{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Poslední galerie</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                            <th class="head1">Stav</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestgalleries)}
                            {foreach $gallery in $latestgalleries}
                                <tr>
                                    <td><a href="/admin/gallery/edit/{echo $gallery->getId()}">{echo $gallery->getTitle()}</a></td>
                                    <td>{echo $gallery->getUserAlias()}</td>
                                    <td>{echo $gallery->getCreated()}</td>
                                    <td>
                                        {if $gallery->getIsPublic() == 1}Veřejná{/if}
                                        {else}Soukromá{/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
</div><!--content-->