<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Dokumenty</a></li>
    <li><a href="/admin/document/upload/">Nahrát Dokument</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Dokumenty</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">Název</td>
                <td class="head1">Typ</td>
                <td class="head0">Autor</td>
                <td class="head1">Vytvořeno</td>
                <td class="head0">Stav</td>
                <td class="head1">&nbsp;</td>
            </tr> 
        </thead>

        <tbody>
            {if !empty($documents)}
                {foreach $document in $documents}
                    <tr>
                        <td>{echo $document->getFilename()}</td>
                        <td>{echo $document->getFormat()}</td>
                        <td>{echo $document->getUserAlias()}</td>
                        <td>{echo $document->getCreated()}</td>
                        <td>
                            {if ($document->active)}<span class="labelProduct labelProductGreen">Aktivní</span>{/if}
                        </td>
                        <td>
                            <a href="/admin/document/changestatus/{echo $document->id}" class="btn btn3 btn_refresh ajaxChangestate" title="Změna stavu"></a>
                            
                            {if $isAdmin || $document->userId == $authUser->id}
                                <a href="/admin/document/delete/{echo $document->id}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                            {/if}
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>