<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/document/">Dokumenty</a></li>
    <li class="current"><a href="#">Nahrát Dokument</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Nahrát Dokument</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2 uploadForm" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="10000000"/>
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="csrf" value="{echo $token}" />

        <p>
            <label>Popis</label>
            <span class="field">
                <textarea rows="5" name="description" class="longinput">{echo isset($file)? $file->description: ""}</textarea>
                {if isset($errors["description"])}
                <label class="error">{echo join("<br/>", $errors["description"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Pořadí<small>Max. 99</small></label>
            <span class="field">
                <input type="text" name="rank" class="longinput" value="{echo isset($file)? $file->rank: 1}"/>
                {if isset($errors["rank"])}
                <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Dokument</label>
            <span class="field">
                Povolené typy: *.rtf, *.txt, *.doc, *.docx, *.xls, *.xlsx, *.pdf, *.ppt, *.pptx, *.zip, *.rar<br/>
                <a href="#" class="btn btn_folder multi_upload"><span>+</span></a>
                <a href="#" class="btn btn_folder multi_upload_dec"><span>-</span></a>
            </span>
            <span class="field file_inputs">
                <input type="file" name="secondfile[]"/>
                {if isset($errors["secondfile"])}
                <label class="error">
                    {echo join("<br/>", $errors["secondfile"])}
                </label>
                {/if}
            </span> 
        </p>

        <p class="stdformbutton">
            <input name="submitAddDocument" type="submit" value="Uložit" class="submit radius2" />
        </p>
    </form>
</div>
