<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/advertisement/">Bazar</a></li>
    <li><a href="/admin/advertisement/sections/">Kategorie</a></li>
    <li><a href="/admin/advertisement/addsection/">Přidat Kategorii</a></li>
    <li class="current"><a href="#">Upravit Kategorii</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Upravit Kategorii</span></h2>
    </div><!--contenttitle-->
    
    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        
        <p>
            <label>Název*</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo $adsection->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $adsection->active == 0}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/if}{else}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditAdSection" type="submit" value="Uložit" class="submit radius2" />
        </p>
    </form>
</div>