<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Bazar</a></li>
    <li><a href="/admin/advertisement/sections/">Kategorie</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Inzeráty</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <input type="hidden" name="type" id="type" value="advertisement" />
    
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable2">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">Id</td>
                <td class="head1">Název</td>
                <td class="head0">Autor</td>
                <td class="head1">Platnost do</td>
                <td class="head0">Vytvořeno</td>
                <td class="head1">Stav</td>
                <td class="head0">&nbsp;</td>
            </tr>
        </thead>
    </table>
</div>
<br class="clear-all"/><br />