<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/advertisement/">Bazar</a></li>
    <li class="current"><a href="#">Kategorie</a></li>
    {if $isAdmin}<li><a href="/admin/advertisement/addsection/">Přidat kategorii</a></li>{/if}
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Kategorie Bazaru</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table border="0" class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">Název</td>
                <td class="head1">Počet inzerátů - Nabídka</td>
                <td class="head0">Počet inzerátů - Poptávka</td>
                <td class="head1">Stav</td>
                <td class="head0">Vytvořeno</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            {if !empty($adsections)}
                {foreach $section in $adsections}
                    <tr>
                        <td>{echo $section->getTitle()}</td>
                        <td>{echo $section->adTenderCount}</td>
                        <td>{echo $section->adDemandCount}</td>
                        <td>{if ($section->active)}<span class="infoLabel infoLabelGreen">Aktivní</span>{/if}</td>
                        <td>{echo $section->getCreated()}</td>
                        <td>
                            {if $isAdmin}<a href="/admin/advertisement/editsection/{echo $section->getId()}" class="btn btn3 btn_pencil" title="Upravit"></a>
                            <a href="/admin/advertisement/deletesection/{echo $section->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>{/if}
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>