<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {if $env == "dev"}<meta http-equiv="Cache-control" content="no-store">{/if}
        
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="description" content="{echo $metadescription}" />
        <meta name="revisit-after" content="1 Day" />
        <meta name="robots" content="{echo $metarobots}">
        <meta name="author" content="Tomas Hodan, Tomas Slama, Lukas Hodan" />
        
        {if isset($article)}
        <meta property="og:title" content="{echo $metatitle}" />
        <meta property="og:type" content="{echo $metaogtype}" />
        <meta property="og:url" content="{echo $metaogurl}" />
        <meta property="og:image" content="{echo $metaogimage}" />
        <meta property="og:description" content="{echo $metadescription}" />
        <meta property="og:site_name" content="{echo $metaogsitename}" />
        <meta property="article:published_time" content="{echo $articlecreated}" />
        <meta property="article:modified_time" content="{echo $articlemodified}" />
        {/if}{else}
        <meta property="og:url" content="{echo $metaogurl}" />
        <meta property="og:title" content="{echo $metatitle}" />
        <meta property="og:description" content="{echo $metadescription}" />
        <meta property="og:type" content="{echo $metaogtype}" />
        <meta property="og:site_name" content="{echo $metaogsitename}" />
        {/else}

        <link href="/public/css/custom/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/custom/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/modernizr.js"></script>

        {if isset($pagedprev) && $pagedprev != 0}<link rel="prev" href="{echo $pagedprevlink}">{/if}
        {if isset($pagednext) && $pagednext != 0}<link rel="next" href="{echo $pagednextlink}">{/if}
        <link rel="canonical" href="{echo $canonical}" />
        <title>{echo $metatitle}</title>
    </head>
    <body lang="cs">
        <div>
            {yield action}
        </div>

        <!-- JS scripts --> 
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>
        <script type="text/javascript" src="/public/js/custom/generalApp.js"></script>
        <!-- End JS scripts -->
    </body>
</html>