<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {if $env == "dev"}<meta http-equiv="Cache-control" content="no-store">{/if}
        
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="description" content="{echo $metadescription}" />
        <meta name="author" content="Tomas Hodan" />
        <meta name="robots" content="{echo $metarobots}" />

        <link href="/public/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/modernizr.js"></script>

        <title></title>
    </head>
    <body lang="cs">
        <div>
            {yield action}
        </div>

        <!-- JS scripts --> 
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>
        <!-- End JS scripts -->
    </body>
</html>